name: shell commands

on:
  - push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello"
      - name: Multi line string
        run: |
          pwd
          df -h
          node -v
          ls -a
  run-shell-commands:
    runs-on: windows-latest
    needs: ["run-shell-commands"]
    steps:        
      - name: Directory
          pwd
          shell: bash